---
version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-0-51"
exclude_patterns:
  - "db/migrations/"
  - "lib/tasks/*.rake"
  - "spec/"
  - "vendor/"
