AllCops:
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/zipcodes.rake'

Metrics/BlockLength:
  Exclude:
    - '**/Gemfile'
    - 'lib/**/*.rake'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
