branch-defaults:
  master:
    environment: staging
global:
  application_name: move.mil
  default_ec2_keyname: move-mil-deployer
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  sc: git
  workspace_type: Application
