branch-defaults:
  master:
    environment: move-mil-staging
  production:
    environment: move-mil-prod
global:
  application_name: move.mil
  default_ec2_keyname: move-mil-deployer
  default_platform: Ruby 2.4 (Puma)
  default_region: us-east-1
  sc: git
  workspace_type: Application
