source: ./src
destination: ./public

gems:
  - bourbon
  - jekyll-assets
  - neat

assets:
  sources:
    - _vendor/assets/fonts
    - _vendor/assets/images
    - _vendor/assets/javascripts
    - _vendor/assets/stylesheets
